const types = {
  Special: [
    "DarkMode",
    "Timeline",
    "SkillBar",
    "Calendar",
    "TypicalDeviceBreakpoints",
    "DraggableHTMLElement",
    "SyntaxHighlighter",
    "CollScroll",
    "Parallax",
    "ScrollDrawing",
    "GradientBgScroll"
  ],

  Templates: [
    "SinglePage",
    "ECommerce",
    "Restaurant",
    "Flowershop",
    "ComingSoonPage"
  ],

  Base: ["Cards", "Cards", "FlipCard", "ProfileCard", "ProductCard"],

  ImageLists: ["QuiltedImageList", "StandardImageList", "WovenImageList"],

  ProgressIndicators: [
    "CircularIndicator",
    "LinearIndicator",
    "ScrollIndicator",
    "ProgressBars"
  ],

  Buttons: [
    "ActionButton",
    "DryButton",
    "ToggleButton",
    "OutlinedButton",
    "ContainedButton",
    "TextButton",
    "AlertButtons",
    "OutlineButtons",
    "SplitButtons",
    "AnimatedButtons",
    "FadingButtons",
    "ButtononImage",
    "SocialMediaButtons",
    "ReadMoreReadLess",
    "LoadingButtons",
    "DownloadButtons",
    "PillButtons",
    "NotificationButton",
    "IconButtons",
    "NextprevButtons",
    "MoreButtoninNav",
    "BlockButtons",
    "TextButtons",
    "RoundButtons",
    "ScrollToTopButton",
    "ToggleLikeDislike"
  ],

  Lists: ["Divider", "SingleLineList", "ThreeLineList", "TwoLineList"],

  UserHelpers: [
    "Banner",
    "Snackbar",
    "Tooltip",
    "Loaders",
    "Alerts",
    "Notes",
    "CountdownTimer",
    "Typewriter"
  ],

  Features: [
    "About",
    "ImageCarousel",
    "Team",
    "Headers1",
    "Header1",
    "Header",
    "SmoothScroll",
    "StickyHeader",
    "ShrinkHeaderOnScroll",
    "Hours",
    "SpotlightGallery",
    "ToDoList",
    "StarRating",
    "UserRating",
    "Coupon",
    "Footer",
    "Pricing",
    "FlipBox",
    "SplitScreen",
    "Testimonials",
    "SectionCounter",
    "QuotesSlideshow"
  ],

  Menus: [
    "Accordion",
    "BottomSheet",
    "SideSheet",
    "AccordionSingle",
    "DropdownMenu",
    "Tab",
    "BottomBar",
    "NavigationDrawer",
    "TopBar",
    "BottomNavigation",
    "NavigationRail",
    "Sidebar",
    "IconBar",
    "MenuIcon",
    "Accordion",
    "Tabs",
    "VerticalTabs",
    "TabHeaders",
    "FullPageTabs",
    "HoverTabs",
    "TopNavigation",
    "ResponsiveTopnav",
    "NavbarWithIcons",
    "SearchMenu",
    "SearchBar",
    "FixedSidebar",
    "SideNavigation",
    "ResponsiveSidebar",
    "FullscreenNavigation",
    "OffCanvasMenu",
    "HoverSidenavButtons",
    "SidebarwithIcons",
    "HorizontalScrollMenu",
    "VerticalMenu",
    "BottomNavigation",
    "ResponsiveBottomNav",
    "BottomBorderNavLinks",
    "RightAlignedMenuLinks",
    "CenteredMenuLink",
    "EqualWidthMenuLinks",
    "FixedMenu",
    "SlideDownBaronScroll",
    "HideNavbaronScroll",
    "ShrinkNavbaronScroll",
    "StickyNavbar",
    "NavbaronImage",
    "HoverDropdowns",
    "ClickDropdowns",
    "DropdowninTopnav",
    "DropdowninSidenav",
    "RespNavbarDropdown",
    "SubnavigationMenu",
    "Dropup",
    "MegaMenu",
    "MobileMenu",
    "CurtainMenu",
    "CollapsedSidebar",
    "CollapsedSidepanel",
    "Pagination",
    "Breadcrumbs",
    "ButtonGroup",
    "VerticalButtonGroup",
    "StickySocialBar",
    "PillNavigation",
    "ResponsiveHeader",
    "TreeView"
  ],

  Forms: [
    "LoginForm",
    "SignupForm",
    "CheckoutForm",
    "ContactForm",
    "SocialLoginForm",
    "RegisterForm",
    "FormWithIcons",
    "Newsletter",
    "StackedForm",
    "ResponsiveForm",
    "PopupForm",
    "InlineForm",
    "ClearInputField",
    "HideNumberArrows",
    "CopyTextToClipboard",
    "AnimatedSearch",
    "SearchButton",
    "FullscreenSearch",
    "InputFieldInNavbar",
    "LoginFormInNavbar",
    "CustomCheckboxRadio",
    "CustomSelect",
    "ToggleSwitch",
    "CheckCheckbox",
    "DetectCapsLock",
    "TriggerButtonOnEnter",
    "PasswordValidation",
    "TogglePasswordVisibility",
    "MultipleStepForm",
    "Autocomplete",
    "TurnOffAutoComplete",
    "TurnOffSpellCheck",
    "FileUploadButton",
    "EmptyInputValidation"
  ],

  FormsHelpers: [
    "Checkbox",
    "Label",
    "SelectionControl",
    "Chip",
    "ContactChips",
    "Password",
    "Slider",
    "DatePicker",
    "Radio",
    "Switch",
    "Input",
    "Select",
    "RangeSliders",
    "CustomScrollbar",
    "ClosableListItems"
  ],

  Filters: [
    "FilterList",
    "FilterTable",
    "FilterElements",
    "FilterDropdown",
    "SortList",
    "SortTable"
  ],

  Modals: [
    "AlertDialog",
    "ConfirmationDialog",
    "SimpleDialog",
    "ModalBox",
    "Popups",
    "OverlayEffect",
    "Callout",
    "Snackbar",
    "ToggleHideShow"
  ],

  Icons: ["Icon", "AnimateIcons"],

  Video: ["FullscreenVideo", "FullscreenWindow"],

  typography: ["Typography"],

  Tabs: ["Plain", "Scrollable"],

  Table: [
    "BaseTable",
    "ZebraStripedTable",
    "ResponsiveTables",
    "ComparisonTable"
  ],

  Grid: [
    "TwoColumnLayout",
    "ThreeColumnLayout",
    "FourColumnLayout",
    "ExpandingGrid",
    "ListGridView",
    "MixedColumnLayout",
    "ColumnCards",
    "ZigZagLayout",
    "BlogLayout"
  ],

  Images: [
    "Slideshow",
    "SlideshowGallery",
    "ModalImages",
    "Lightbox",
    "ResponsiveImageGrid",
    "ImageGrid",
    "TabGallery",
    "ImageOverlayFade",
    "ImageOverlaySlide",
    "ImageOverlayZoom",
    "ImageOverlayTitle",
    "ImageOverlayIcon",
    "ImageEffects",
    "BlackAndWhiteImage",
    "ImageText",
    "ImageTextBlocks",
    "TransparentImageText",
    "FullPageImage",
    "FormonImage",
    "HeroImage",
    "BlurBackgroundImage",
    "ChangeBgonScroll",
    "SidebySideImages",
    "RoundedImages",
    "AvatarImages",
    "ResponsiveImages",
    "CenterImages",
    "Thumbnails",
    "BorderAroundImage",
    "MeettheTeam",
    "StickyImage",
    "FlipanImage",
    "ShakeanImage",
    "PortfolioGallery",
    "PortfoliowithFiltering",
    "ImageZoom",
    "ImageMagnifierGlass",
    "ImageComparisonSlider"
  ],

  Iframs: ["ResponsiveIframes", "GetIframeElements"],

  Chat: ["ChatMessages", "PopupChatWindow"]
};
